<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-MUQUGSJ" name="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest" tests="10" failures="2" timestamp="12 Jan 2019 18:14:27 GMT" time="639.747" errors="0">
  <testcase name="validateSignInPage_PageHeading_SIP" time="90.484" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateSignInPage_PageHeading_SIP" time="25.289" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateSignInPage_SignInSectionHeading_SIP" time="42.895" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateSignInPage_SignInSectionHeading_SIP" time="84.290" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateSignInPageBreadcrumbText_SIP" time="48.286" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateSignInPageBreadcrumbText_SIP" time="83.995" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateRegistrationSectionHeading_SignInPage_SIP" time="33.138" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateRegistrationSectionHeading_SignInPage_SIP" time="100.969" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateLoginProcess_SIP" time="35.903" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest">
    <failure type="java.lang.AssertionError" message="expected [MY ACCOUNT] but found [AUTHENTICATION]">
      <![CDATA[java.lang.AssertionError: expected [MY ACCOUNT] but found [AUTHENTICATION]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest.validateLoginProcess_SIP(SignInTest.java:212)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- validateLoginProcess_SIP -->
  <testcase name="validateLoginProcess_SIP" time="94.498" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest">
    <failure type="java.lang.AssertionError" message="expected [MY ACCOUNT] but found [AUTHENTICATION]">
      <![CDATA[java.lang.AssertionError: expected [MY ACCOUNT] but found [AUTHENTICATION]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest.validateLoginProcess_SIP(SignInTest.java:212)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- validateLoginProcess_SIP -->
</testsuite> <!-- com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest -->
