<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-MUQUGSJ" ignored="1" name="CHTest1-SignInTest" tests="5" failures="1" timestamp="12 Jan 2019 17:42:04 GMT" time="188.516" errors="0">
  <testcase name="validateSignInPage_PageHeading_SIP" time="0.686" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateSignInPage_SignInSectionHeading_SIP" time="0.67" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateSignInPageBreadcrumbText_SIP" time="0.693" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateRegistrationSectionHeading_SignInPage_SIP" time="0.66" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateLoginProcess_SIP" time="3.21" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest">
    <failure type="java.lang.AssertionError" message="expected [MY ACCOUNT] but found [AUTHENTICATION]">
      <![CDATA[java.lang.AssertionError: expected [MY ACCOUNT] but found [AUTHENTICATION]
at com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest.validateLoginProcess_SIP(SignInTest.java:212)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- validateLoginProcess_SIP -->
  <testcase name="validateForgotPasswordLink_SIP" time="0.0" classname="com.a3hp.automationpracticee.framework.test.createaccountandlogin.SignInTest">
    <ignored/>
  </testcase> <!-- validateForgotPasswordLink_SIP -->
</testsuite> <!-- CHTest1-SignInTest -->
